name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set IMAGE_TAG
      run: echo "IMAGE_TAG=$(date +%Y%m%d)-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    # 登录 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # 构建镜像
    - name: Build the Docker image
      run: docker build -t purewhiteicecream/mihomo_sub:${{ env.IMAGE_TAG }} -t purewhiteicecream/mihomo_sub:latest .

    # 推送镜像
    - name: Push Docker image
      run: |
        docker push purewhiteicecream/mihomo_sub:${{ env.IMAGE_TAG }}
        docker push purewhiteicecream/mihomo_sub:latest